apiVersion: v1
kind: Pod
metadata:
  name: ollama-pod
  namespace: ollama
spec:
  containers:
  - name: ollama
    image: ollama/ollama:latest
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
    ports:
    - containerPort: 11434
  restartPolicy: Always